import Advents.Utils
import Advents.day01
import Advents.day02
import Advents.day02_syntax
import Advents.day02_traditional
import Advents.day03
import Advents.day04
import Advents.day05
import Advents.day06
import Advents.day07
import Advents.day08
import Advents.day09
import Advents.day10
import Advents.day11
import Advents.day12
import Advents.day13
import Advents.day14
import Advents.day15
import Advents.day16
import Advents.day18
import Advents.day19
import Advents.day20
import Advents.day21
import Advents.day22
import Advents.day23
import Advents.day24
import Advents.day25
