name: PR Summary
on:
  pull_request:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  pr-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: adomani/PR_summary/@dev
