name: PR Summary
on:
  pull_request_target:

# Limit permissions for GITHUB_TOKEN for the entire workflow
permissions:
  contents: read
  pull-requests: write  # Only allow PR comments/labels
  # All other permissions are implicitly 'none'

jobs:
  pr-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: adomani/PR_summary/@dev
        with:
          IMPORT_DIFF: true
          CUSTOM_REPORT_SCRIPT: ".src/technical-debt-metrics.sh"
          CUSTOM_REPORT_SCRIPT_ARGUMENTS: "pr_summary; echo '${{ github.repository }}'"
